# Generated for DACHApply MVP
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='InviteCode', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('code', models.CharField(max_length=80, unique=True)),('label', models.CharField(blank=True, max_length=120)),('active', models.BooleanField(default=True)),('expires_at', models.DateTimeField(blank=True, null=True)),('created_at', models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='JobLead', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('company', models.CharField(max_length=200)),('title', models.CharField(max_length=250)),('location', models.CharField(blank=True, max_length=200)),('url', models.URLField(blank=True, max_length=1000)),('source', models.CharField(blank=True, max_length=120)),('raw_description', models.TextField(blank=True)),('submitted_by', models.CharField(blank=True, max_length=120)),('submitter_reason', models.TextField(blank=True)),('salary_info', models.CharField(blank=True, max_length=250)),('language_requirements', models.CharField(blank=True, max_length=250)),('work_mode', models.CharField(choices=[('onsite','Onsite'),('hybrid','Hybrid'),('remote','Remote'),('unknown','Unknown')], default='unknown', max_length=20)),('status', models.CharField(choices=[('new','New'),('reviewed','Reviewed'),('to_apply','To apply'),('applied','Applied'),('interview','Interview'),('rejected','Rejected'),('skipped','Skipped'),('archived','Archived')], default='new', max_length=20)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='JobEvaluation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('fit_score', models.IntegerField()),('priority', models.CharField(choices=[('high','High'),('medium','Medium'),('low','Low')], max_length=10)),('recommendation', models.CharField(choices=[('apply','Apply'),('maybe','Maybe'),('skip','Skip')], max_length=10)),('summary', models.TextField(blank=True)),('main_match_reasons', models.JSONField(default=list)),('main_gaps', models.JSONField(default=list)),('required_skills', models.JSONField(default=list)),('nice_to_have_skills', models.JSONField(default=list)),('matched_skills', models.JSONField(default=list)),('missing_skills', models.JSONField(default=list)),('cv_adjustment_notes', models.TextField(blank=True)),('interview_prep_notes', models.TextField(blank=True)),('risk_notes', models.TextField(blank=True)),('next_action', models.TextField(blank=True)),('structured_json_raw', models.JSONField(default=dict)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='jobradar.joblead'))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='FollowUp', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('follow_up_date', models.DateField()),('reason', models.CharField(max_length=250)),('completed', models.BooleanField(default=False)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='jobradar.joblead'))], options={'ordering':['completed','follow_up_date']}),
        migrations.CreateModel(name='ApplicationNote', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('note', models.TextField()),('note_type', models.CharField(choices=[('general','General'),('cv_change','CV change'),('recruiter_message','Recruiter message'),('interview_prep','Interview prep'),('rejection_feedback','Rejection feedback'),('follow_up','Follow up')], default='general', max_length=30)),('created_at', models.DateTimeField(auto_now_add=True)),('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobradar.joblead'))], options={'ordering':['-created_at']}),
    ]
