# Generated by Django 5.2.14 on 2026-06-05 14:12

from django.db import migrations, models

DEFAULT_CANDIDATE_PROFILE = '''Software Engineer based in Vienna. Strong Python backend experience. Django, FastAPI, REST APIs, Java. RAG, semantic search, LangChain, LangGraph. Elasticsearch/OpenSearch. SQL, PostgreSQL, MySQL. Docker, Linux, Kubernetes basics, AWS basics, Azure learning in progress. RabbitMQ, Redis, async/background processing from personal projects. Enterprise background in finance, telecom, and AI/search systems. German: professional working proficiency, B2 completed, C1 in progress. English: C2 certified. Stronger fit for Python Backend, AI Engineer, RAG, Search, Data Engineering, Platform, and reliability-focused roles. Weaker fit for frontend-heavy React/TypeScript roles, pure DevOps/SRE roles, pure ML research roles, and roles requiring deep professional cloud/Spark/Terraform experience. Do not invent experience. Be honest about gaps and hiring risk.'''

FIELDS = [
    ('candidate_profile', DEFAULT_CANDIDATE_PROFILE),
    ('language_levels', ''),
    ('preferred_locations', ''),
    ('preferred_stack', ''),
    ('red_flags', ''),
    ('salary_expectations', ''),
    ('selling_points', ''),
    ('target_roles', ''),
]


def add_missing_profile_columns(apps, schema_editor):
    table = 'jobradar_userprofile'
    existing = {col.name for col in schema_editor.connection.introspection.get_table_description(schema_editor.connection.cursor(), table)}
    qn = schema_editor.quote_name
    for field, default in FIELDS:
        if field in existing:
            continue
        # Keep a database default so adding NOT NULL columns works for existing
        # rows. Parameters are not portable in DDL, so quote single quotes.
        escaped = default.replace("'", "''")
        schema_editor.execute(f"ALTER TABLE {qn(table)} ADD COLUMN {qn(field)} text NOT NULL DEFAULT '{escaped}'")


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0009_friend_request_approval'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_missing_profile_columns, migrations.RunPython.noop)],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='candidate_profile',
                    field=models.TextField(blank=True, default=DEFAULT_CANDIDATE_PROFILE),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='language_levels',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='preferred_locations',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='preferred_stack',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='red_flags',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='salary_expectations',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='selling_points',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='target_roles',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
