# Generated by Django 5.2.14 on 2026-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0012_userdailyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('authenticated_count', models.PositiveIntegerField(default=0)),
                ('anonymous_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
