# Generated by Django 5.2.14 on 2026-06-12 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0015_scheduledtaskrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedailyusage',
            name='demo_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitedailyusage',
            name='demo_unique_visitor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitedailyusage',
            name='unique_visitor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('demo_click_count', models.PositiveIntegerField(default=0)),
                ('demo_last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('demo_click_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('demo_last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='jobradar.sitevisitor')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('visitor', 'date')},
            },
        ),
    ]
