# Generated by Django 5.2.14 on 2026-06-12 11:40

from django.db import migrations, models


def backfill_visitor_flags(apps, schema_editor):
    SiteVisitor = apps.get_model('jobradar', 'SiteVisitor')
    VisitorDailyUsage = apps.get_model('jobradar', 'VisitorDailyUsage')
    SiteVisitor.objects.filter(user_id__isnull=True).update(had_anonymous=True)
    SiteVisitor.objects.filter(user_id__isnull=False).update(had_authenticated=True)
    SiteVisitor.objects.filter(demo_click_count__gt=0).update(had_anonymous=True)
    VisitorDailyUsage.objects.filter(visitor__user_id__isnull=True).update(had_anonymous=True)
    VisitorDailyUsage.objects.filter(visitor__user_id__isnull=False).update(had_authenticated=True)
    VisitorDailyUsage.objects.filter(demo_click_count__gt=0).update(had_anonymous=True)


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0016_sitedailyusage_demo_click_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='had_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='had_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitordailyusage',
            name='had_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitordailyusage',
            name='had_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_visitor_flags, migrations.RunPython.noop),
    ]
