# Generated by Django 5.2.14 on 2026-07-16 06:52

from django.db import migrations, models


def preserve_existing_descriptions(apps, schema_editor):
    JobLead=apps.get_model('jobradar', 'JobLead')
    JobLead.objects.update(original_source_text=models.F('raw_description'))


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0018_delete_non_demo_demo_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='original_source_text',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(preserve_existing_descriptions, migrations.RunPython.noop),
    ]
