# Generated by Django 5.2.17 on 2026-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0020_userprofile_learned_application_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='applied_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('to_apply', 'To apply'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('skipped', 'Skipped'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
