# Generated by Django 5.2.17 on 2026-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0022_backfill_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='apply_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblead',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblead',
            name='interview_note',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
