# Generated by Django 5.2.17 on 2026-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0023_joblead_apply_by_joblead_interview_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow_up_digest_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
