# Generated by Django 5.2.17 on 2026-08-16 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_codes(apps, schema_editor):
    """Hand pre-TASK-92 codes to the account that has been using them.

    Every code that exists today was typed into Django admin by the single deployment's
    owner, so "the current owner" is the earliest superuser, then the earliest staff user.
    Both lookups can legitimately come back empty -- a fresh checkout or CI runs this on a
    database with no users at all -- in which case the codes stay ownerless, which is exactly
    their behaviour before this migration (submission lands unowned, staff-only). Never
    raises, never guesses a non-admin account.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    owner = User.objects.filter(is_superuser=True).order_by('pk').first() or User.objects.filter(is_staff=True).order_by('pk').first()
    if owner:
        apps.get_model('jobradar', 'InviteCode').objects.filter(owner__isnull=True).update(owner=owner)


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0025_candidate_profile_default_and_candidate_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invitecode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_codes, migrations.RunPython.noop),
    ]
