# Generated by Django 5.2.17 on 2026-08-16 14:04
#
# TASK-93 AC3 is this file's default=True and nothing else: AddField writes the default into every
# existing row, so every account that already had a profile lands grandfathered as verified. No data
# migration, and no backfill to forget -- accounts with no profile row at all are handled in
# services.email_verification.is_email_verified().

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0027_userprofile_can_generate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_friend_lookup',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
