# Generated by Django 5.2.17 on 2026-08-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0028_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=300)),
                ('answer_text', models.TextField()),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=2)),
                ('clarity_score', models.PositiveSmallIntegerField()),
                ('structure_score', models.PositiveSmallIntegerField()),
                ('confidence_score', models.PositiveSmallIntegerField()),
                ('overall_score', models.PositiveSmallIntegerField()),
                ('feedback', models.JSONField(default=list)),
                ('stronger_answer', models.TextField(blank=True, default='')),
                ('evaluator', models.CharField(default='heuristic', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='jobradar.joblead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
