# Generated by Django 5.2.17 on 2026-08-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0029_practicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, choices=[('', 'Not skipped'), ('quiet_hours', 'Calendar busy')], default='', max_length=20)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('job_related_count', models.PositiveIntegerField(default=0)),
                ('uncertain_count', models.PositiveIntegerField(default=0)),
                ('suggestion_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_check_cadence_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_check_calendar_aware',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MailboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('message_id', models.CharField(blank=True, default='', max_length=250)),
                ('sender', models.CharField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('rejection', 'Rejection'), ('interview_invitation', 'Interview invitation'), ('offer', 'Offer'), ('recruiter_reply', 'Recruiter reply'), ('uncertain', 'Uncertain'), ('not_job_related', 'Not job related')], default='uncertain', max_length=30)),
                ('evaluator', models.CharField(default='heuristic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_messages', to='jobradar.joblead')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobradar.mailboxrun')),
            ],
            options={
                'ordering': ['-uid'],
            },
        ),
        migrations.CreateModel(
            name='MailboxSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('status_change', 'Status change'), ('interview_date', 'Interview date'), ('feedback_clear', 'Feedback clock clear')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_suggestions', to='jobradar.joblead')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='jobradar.mailboxmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
