# Generated by Django 5.2.17 on 2026-08-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0030_mailboxrun_userprofile_mailbox_check_cadence_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxrun',
            name='draft_blocked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailboxrun',
            name='draft_written_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_do_not_disclose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_salary_floor_eur',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MailboxDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('written', 'Written to Gmail Drafts'), ('blocked', 'Blocked')], max_length=10)),
                ('block_reason', models.CharField(blank=True, default='', max_length=250)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('evaluator', models.CharField(default='template', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_drafts', to='jobradar.joblead')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='jobradar.mailboxmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
