# Generated by Django 5.2.17 on 2026-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0031_mailboxrun_draft_blocked_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='gmail_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='internal_date_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
