# Generated by Django 5.2.17 on 2026-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0032_mailboxmessage_gmail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxrun',
            name='drafting_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
