# Generated by Django 5.2.17 on 2026-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0033_mailboxrun_drafting_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_generate_cv',
            field=models.BooleanField(default=False, help_text="Generates CVs and cover letters from the site owner's private LaTeX templates and the owner's own photograph, and writes them into a shared output directory on the server -- not this account's own templates or photo."),
        ),
    ]
