# Generated by Django 5.2.17 on 2026-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0034_alter_userprofile_can_generate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_calendar_ics_urls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
