# Generated by Django 5.2.17 on 2026-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0035_userprofile_mailbox_calendar_ics_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
