# Generated by Django 5.2.17 on 2026-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0036_mailboxmessage_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxdraft',
            name='gmail_draft_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailboxdraft',
            name='gmail_message_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailboxdraft',
            name='gmail_thread_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='thread_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
