# Generated by Django 5.2.17 on 2026-08-18 16:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0037_mailboxdraft_gmail_draft_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_check_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_check_window_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_check_window_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='mailboxrun',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('', 'Not skipped'), ('quiet_hours', 'Calendar busy'), ('disabled', 'Checking turned off'), ('outside_window', 'Outside the allowed time window')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='MailboxCheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='jobradar.mailboxrun')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
