# Generated by Django 5.2.17 on 2026-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0038_userprofile_mailbox_check_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskrun',
            name='running_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
