# Generated by Django 5.2.17 on 2026-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0039_scheduledtaskrun_running_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxdraft',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_chat_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_chat_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
