# Generated by Django 5.2.17 on 2026-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0040_mailboxdraft_chat_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='cc_addrs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='reply_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='sent_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='to_addrs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
