# Generated by Django 5.2.17 on 2026-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0041_mailboxmessage_to_cc_reply_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_organizer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mailboxmessage',
            name='classification',
            field=models.CharField(choices=[('rejection', 'Rejection'), ('interview_invitation', 'Interview invitation'), ('offer', 'Offer'), ('recruiter_reply', 'Recruiter reply'), ('application_confirmed', 'Application confirmed'), ('uncertain', 'Uncertain'), ('not_job_related', 'Not job related')], default='uncertain', max_length=30),
        ),
    ]
