# Generated by Django 5.2.17 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0042_mailboxmessage_widened_fetch_and_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_lookback_months',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
