# Generated by Django 5.2.17 on 2026-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0043_userprofile_mailbox_lookback_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='board_sort_keys',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
