# Generated by Django 5.2.17 on 2026-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0044_userprofile_board_sort_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='calendar_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
