# Generated by Django 5.2.17 on 2026-08-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0046_userprofile_mailbox_calendar_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxrun',
            name='suggestion_blocked_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
