# Generated by Django 5.2.17 on 2026-08-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0047_mailboxrun_suggestion_blocked_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxmessage',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailbox_identify_window_months',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
