"""TASK-99a: per-account CV templates and photograph.

Schema only. The owner's existing files are moved in by the import_cv_assets management command,
which is dry-run by default -- deliberately not here, because a migration runs unattended on every
deployment including production, where CODEX_CV_WORKSPACE is empty and none of those files exist,
and because it would have to guess which account they belong to.
"""
# Generated by Django 5.2.17 on 2026-08-24 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0048_mailboxmessage_dismissed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_generate_cv',
            field=models.BooleanField(default=False, help_text="Generates CVs and cover letters from this account's own LaTeX templates and photograph, and writes them into a shared output directory on the server. An account with no templates of its own cannot generate anything."),
        ),
        migrations.CreateModel(
            name='CvAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'CV template'), ('letter', 'Letter template'), ('photo', 'Photograph')], max_length=10)),
                ('key', models.CharField(blank=True, default='', max_length=40)),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.TextField(blank=True, default='')),
                ('image', models.BinaryField(blank=True, default=b'')),
                ('source_path', models.CharField(blank=True, default='', max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'kind', 'key'],
                'unique_together': {('user', 'kind', 'key')},
            },
        ),
    ]
