# Generated by Django 5.2.17 on 2026-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0049_alter_userprofile_can_generate_cv_cvasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxsuggestion',
            name='postponed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailboxsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('postponed', 'Postponed')], default='pending', max_length=10),
        ),
    ]
