# Generated by Django 5.2.17 on 2026-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0051_followup_sent_at_mailboxdraft_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblead',
            name='language_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joblead',
            name='salary_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joblead',
            name='source',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
