# Generated by Django 5.2.17 on 2026-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0053_job_source_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('to_apply', 'To apply'), ('ready_to_submit', 'Ready to submit'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('skipped', 'Skipped'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
