# Generated by Django 5.2.17 on 2026-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobradar', '0055_userprofile_board_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='dismissed_source_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
