export type Evaluation={id:number;job:number;fit_score:number;priority:'high'|'medium'|'low';recommendation:'apply'|'maybe'|'skip';summary:string;main_match_reasons:string[];main_gaps:string[];required_skills:string[];nice_to_have_skills:string[];matched_skills:string[];missing_skills:string[];cv_adjustment_notes:string;interview_prep_notes:string;risk_notes:string;next_action:string;skill_statuses?:Record<string,string>;created_at:string}
export type Job={id:number;company:string;title:string;location:string;url:string;source:string;raw_description:string;original_source_text?:string;submitted_by:string;submitter_reason:string;salary_info:string;language_requirements:string;work_mode:string;status:string;status_date?:string|null;interview_stage?:number|null;interview_total?:number|null;interview_at?:string|null;interview_note?:string;apply_by?:string|null;last_update_date?:string|null;feedback_due_date?:string|null;created_by_username?:string;created_by_email?:string;submitted_for_username?:string;submitted_for_email?:string;created_at:string;updated_at?:string;latest_evaluation?:Evaluation|null}
export type FollowUp={id:number;job:number;company:string;title:string;follow_up_date:string;reason:string;completed:boolean}
// /api/stats/ funnel + source rows. Rates are number|null on purpose: null is "no denominator yet",
// which must never render as 0% ("you convert nothing"). `offers` here is *reached* offer over the
// application cohort - a different measure from the flat stats.offers, which is *currently* in offer.
export type FunnelCounts={applications:number;interviews:number;offers:number;applied_to_interview_rate:number|null;interview_to_offer_rate:number|null}
export type Funnel={recent_window_days:number;recent_window_start:string;all_time:FunnelCounts;recent:FunnelCounts;interviews_without_application:number}
export type SourceEffectiveness={source:string;applications:number;interviews:number;interview_rate:number|null}
export type Stats={funnel?:Funnel;source_effectiveness?:SourceEffectiveness[];[key:string]:any}
export type CandidateProfile={candidate_profile:string;candidate_evidence:string;target_roles:string;preferred_locations:string;salary_expectations:string;language_levels:string;preferred_stack:string;red_flags:string;selling_points:string;learned_application_preferences:string;follow_up_digest_enabled:boolean;evaluation_prompt_template:string;combined_prompt_template:string;enrichment_prompt_template:string;bulk_links_prompt_template:string}
export type InviteCode={id:number;code:string;label:string;active:boolean;expires_at:string|null;created_at:string}
